//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int IdProducto { get; set; }
        public string nombre_producto { get; set; }
        public string descripcion_producto { get; set; }
        public string condiciones_uso { get; set; }
        public int IdCategoria { get; set; }
        public int IdBrand { get; set; }
        public string Imagen { get; set; }
        public string Lote { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
