//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalSite.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int IdStock { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdPago { get; set; }
        public string estado { get; set; }
        public string CodigoBP { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
        public Nullable<long> monto_pagado { get; set; }
    
        public virtual Pago Pago { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
